# Generated by Django 3.2.7 on 2022-05-26 22:26

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=250, unique=True, verbose_name='Mois')),
                ('tarif', models.CharField(max_length=250, unique=True, verbose_name='Tarif (FG)')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250, unique=True, verbose_name='Titre')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titre', unique=True)),
                ('texte1', models.TextField(verbose_name='Descrition 1')),
                ('texte2', models.TextField(verbose_name='Descrition 2')),
                ('texte3', models.TextField(verbose_name='Descrition 3')),
                ('image1', models.ImageField(blank=True, upload_to='photos', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, upload_to='photos', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, upload_to='photos', verbose_name='Image 3')),
                ('bg', models.ImageField(blank=True, upload_to='photos', verbose_name='Background')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=250, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom')),
                ('numero', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.formation', verbose_name='Choisir Votre Formation')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
