# Generated by Django 3.2.7 on 2022-05-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='numero',
            field=models.IntegerField(max_length=250),
        ),
    ]
