# Generated by Django 3.2.7 on 2022-05-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_pub_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='image3',
        ),
        migrations.AlterField(
            model_name='pub',
            name='url',
            field=models.CharField(max_length=250, verbose_name='Video Url'),
        ),
    ]
