# Generated by Django 3.2.7 on 2022-06-05 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_formationinformatique_messageinfortique_pubinformatique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationinformatique',
            name='tarif',
            field=models.CharField(max_length=250, verbose_name='Tarif (FG)'),
        ),
        migrations.AlterField(
            model_name='messageinfortique',
            name='formation',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.formationinformatique', verbose_name='Choisir Votre Formation'),
        ),
    ]
