# Generated by Django 3.2.7 on 2022-06-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20220605_0101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageInfortique',
            new_name='MessageInformatique',
        ),
    ]
