# Generated by Django 3.2.7 on 2022-09-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_messageinfortique_messageinformatique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=250, unique=True, verbose_name='Mois')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='messageinformatique',
            name='formation',
        ),
        migrations.DeleteModel(
            name='Pub',
        ),
        migrations.DeleteModel(
            name='PubInformatique',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='FormationInformatique',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageInformatique',
        ),
    ]
