# Generated by Django 3.2.7 on 2022-09-21 03:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20220921_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=250, unique=True, verbose_name='Classes')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='classe', unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=2, editable=False, populate_from='annee', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='annee',
            field=models.CharField(max_length=250, unique=True, verbose_name='Année Scolaire'),
        ),
    ]
