# Generated by Django 3.2.7 on 2022-09-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20220921_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='annee',
            field=models.CharField(default='', max_length=250, unique=True, verbose_name='Année Scolaire'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='classe',
            field=models.CharField(default='', max_length=250, unique=True, verbose_name='Classes'),
        ),
    ]
