# Generated by Django 3.2.7 on 2022-09-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20220921_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anneescolaire',
            old_name='complete',
            new_name='active',
        ),
    ]
