# Generated by Django 3.2.7 on 2022-09-21 03:44

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_rename_complete_anneescolaire_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(default='', max_length=250, unique=True, verbose_name='Année Scolaire')),
                ('debut_inscription', models.CharField(default='', max_length=250, unique=True, verbose_name="Début d'inscription")),
                ('fin_inscription', models.CharField(default='', max_length=250, unique=True, verbose_name="fin d'inscription")),
                ('debut_cours', models.CharField(default='', max_length=250, unique=True, verbose_name='Début des cours')),
                ('fin_cours', models.CharField(default='', max_length=250, unique=True, verbose_name='Fin des cours')),
                ('active', models.BooleanField(default=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='annee', unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='AnneeScolaire',
        ),
    ]
