# Generated by Django 3.2.7 on 2022-09-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20220921_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=250, verbose_name='Prénom')),
                ('naissance', models.CharField(default='01.01.2022', max_length=250, verbose_name='Date de naissance')),
                ('filiation', models.CharField(default='Fils de --- et de --- ', max_length=250, verbose_name='Filiation')),
                ('numero', models.CharField(blank=True, max_length=250, verbose_name='Numero')),
                ('matricule', models.CharField(blank=True, max_length=250, verbose_name='Matricule')),
            ],
            options={
                'ordering': ('prenom',),
            },
        ),
        migrations.AlterField(
            model_name='rentree',
            name='annee',
            field=models.CharField(default='2000-2023', max_length=250, unique=True, verbose_name='Année Scolaire'),
        ),
        migrations.AlterField(
            model_name='rentree',
            name='debut_cours',
            field=models.CharField(default='01.01.2000', max_length=250, unique=True, verbose_name='Début des cours'),
        ),
        migrations.AlterField(
            model_name='rentree',
            name='debut_inscription',
            field=models.CharField(default='01.01.2000', max_length=250, unique=True, verbose_name="Début d'inscription"),
        ),
        migrations.AlterField(
            model_name='rentree',
            name='fin_cours',
            field=models.CharField(default='01.01.2000', max_length=250, unique=True, verbose_name='Fin des cours'),
        ),
        migrations.AlterField(
            model_name='rentree',
            name='fin_inscription',
            field=models.CharField(default='01.01.2000', max_length=250, unique=True, verbose_name="fin d'inscription"),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.rentree', verbose_name='Année Scolaire')),
                ('classe', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.classe', verbose_name='Classes')),
                ('etudiant', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.etudiant', verbose_name='Étudiants')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
