# Generated by Django 3.2.7 on 2022-09-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20220921_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Photo/images', verbose_name='Choisir la photo'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='urgent',
            field=models.CharField(default=2, max_length=250, verbose_name="Contact en cas d'urgence"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=250, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='numero',
            field=models.CharField(max_length=250, verbose_name='Numero'),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=250, verbose_name='Prénom')),
                ('naissance', models.CharField(default='01.01.2022', max_length=250, verbose_name='Date de naissance')),
                ('numero', models.CharField(max_length=250, verbose_name='Numero')),
                ('matricule', models.CharField(max_length=250, verbose_name='Matricule')),
                ('matiere', models.CharField(max_length=250, verbose_name='Matières')),
                ('photo', models.ImageField(blank=True, upload_to='Photo/images', verbose_name='Choisir la photo')),
                ('classe', models.ManyToManyField(default='', null=True, to='apps.Classe', verbose_name='Classes')),
            ],
            options={
                'ordering': ('prenom',),
            },
        ),
    ]
