# Generated by Django 3.2.7 on 2022-09-21 05:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20220921_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(default='', max_length=250, unique=True, verbose_name='Matières')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='matiere', unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='matiere',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matiere',
            field=models.ManyToManyField(null=True, to='apps.Matiere', verbose_name='Matières'),
        ),
    ]
