# Generated by Django 3.2.7 on 2022-09-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_auto_20220921_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name=" Nom de l'établissement")),
                ('numero', models.CharField(max_length=250, verbose_name='Numéro')),
                ('email', models.CharField(max_length=250, verbose_name='E-mail')),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('Directeur', models.CharField(max_length=250, verbose_name='Nom du directeur')),
                ('logo', models.ImageField(blank=True, upload_to='Photo/images', verbose_name='Choisir le logo')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ('matiere',)},
        ),
    ]
