# Generated by Django 3.2.7 on 2022-09-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20220921_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='scolarite',
            field=models.IntegerField(default=3, verbose_name='Scolarite (GNF) '),
            preserve_default=False,
        ),
    ]
