# Generated by Django 3.2.7 on 2022-09-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_inscription_scolarite'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='lieu',
            field=models.CharField(default=2, max_length=250, verbose_name='Lieu de naissance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiation',
            field=models.CharField(default='Fils de et de ', max_length=250, verbose_name='Filiation'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='numero',
            field=models.CharField(max_length=250, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='urgent',
            field=models.CharField(max_length=250, verbose_name="Numéro à contacter en cas d'urgence"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='scolarite',
            field=models.IntegerField(verbose_name='Scolarite (GNF)'),
        ),
    ]
