# Generated by Django 3.2.7 on 2022-09-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20220923_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(max_length=250, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='numero',
            field=models.CharField(max_length=250, unique=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=250, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='numero',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='Numéro'),
        ),
    ]
