# Generated by Django 3.2.7 on 2022-09-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_auto_20220924_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='annee',
            field=models.CharField(default='2020-2020', max_length=250, unique=True, verbose_name='Année Scolaire'),
        ),
    ]
