# Generated by Django 3.2.7 on 2022-10-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_etablissement_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date',
            field=models.CharField(default='01.01.2022', max_length=250, verbose_name="Date d'inscription"),
        ),
    ]
