# Generated by Django 3.2.7 on 2022-10-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_scolarite'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('Inscription', 'Inscription')], default=1, max_length=250, verbose_name='Inscription'),
        ),
    ]
