# Generated by Django 3.2.7 on 2022-10-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_remove_inscription_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='annee',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.rentree', verbose_name='Année Scolaire'),
        ),
    ]
