# Generated by Django 3.2.7 on 2022-10-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_auto_20221005_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scolarite',
            name='classe',
        ),
    ]
