# Generated by Django 3.2.7 on 2022-10-08 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_remove_scolarite_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scolarite',
            name='etudiant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inscription', to='apps.inscription', verbose_name='Étudiants'),
        ),
    ]
