# Generated by Django 3.2.7 on 2022-10-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_alter_scolarite_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='classe',
            field=models.ManyToManyField(null=True, to='apps.Classe', verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='scolarite',
            name='annee',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentree', to='apps.rentree', verbose_name='Année Scolaire'),
        ),
    ]
