# Generated by Django 3.2.7 on 2022-10-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_auto_20221012_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='classe',
            field=models.ManyToManyField(to='apps.Classe', verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='matiere',
            field=models.ManyToManyField(related_name='area', to='apps.Matiere', verbose_name='Matières'),
        ),
    ]
