# Generated by Django 3.2.7 on 2022-10-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_auto_20221021_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ('etudiant',)},
        ),
    ]
