# Generated by Django 3.2.7 on 2022-11-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_alter_inscription_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='annee',
        ),
    ]
