# Generated by Django 3.2.7 on 2022-11-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_remove_etablissement_annee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentree',
            name='active',
        ),
        migrations.AlterField(
            model_name='rentree',
            name='annee',
            field=models.CharField(default='2000-2000', max_length=250, unique=True, verbose_name='Année Scolaire'),
        ),
        migrations.AlterField(
            model_name='rentree',
            name='debut_cours',
            field=models.CharField(default='00.00.2000', max_length=250, unique=True, verbose_name='Début des cours'),
        ),
        migrations.AlterField(
            model_name='rentree',
            name='debut_inscription',
            field=models.CharField(default='00.00.2000', max_length=250, unique=True, verbose_name="Début d'inscription"),
        ),
        migrations.AlterField(
            model_name='rentree',
            name='fin_cours',
            field=models.CharField(default='00.00.2000', max_length=250, unique=True, verbose_name='Fin des cours'),
        ),
        migrations.AlterField(
            model_name='rentree',
            name='fin_inscription',
            field=models.CharField(default='00.00.2000', max_length=250, unique=True, verbose_name="fin d'inscription"),
        ),
    ]
