# Generated by Django 3.2.7 on 2022-11-09 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_auto_20221102_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire', models.IntegerField(verbose_name='Salaire (GNF)')),
                ('date', models.CharField(default='01.01.2022', max_length=250, verbose_name='Date du Payement')),
                ('annee', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annees', to='apps.rentree', verbose_name='Années')),
                ('enseignant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to='apps.enseignant', verbose_name='Enseignants')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
