# Generated by Django 3.2.7 on 2022-11-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_auto_20221109_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='commentaire',
            field=models.CharField(default=2, max_length=250, verbose_name='Commentaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='date',
            field=models.CharField(default='01.01.2022', max_length=250, verbose_name='Date'),
        ),
    ]
