# Generated by Django 3.2.7 on 2022-11-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_auto_20221109_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etablissement',
            old_name='Directeur',
            new_name='directeur',
        ),
        migrations.AlterField(
            model_name='charge',
            name='commentaire',
            field=models.TextField(verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='date',
            field=models.CharField(default='01.01.2022', max_length=250, verbose_name='Date du Paiement'),
        ),
        migrations.AlterField(
            model_name='scolarite',
            name='date',
            field=models.CharField(default='01.01.2022', max_length=250, verbose_name='Date du Paiement'),
        ),
        migrations.AlterField(
            model_name='scolarite',
            name='payement',
            field=models.IntegerField(verbose_name='Paiement (GNF)'),
        ),
    ]
