# Generated by Django 3.2.7 on 2022-11-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_auto_20221114_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='scolarite',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Fevrier', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet')], default=1, max_length=250, verbose_name='Mois'),
        ),
    ]
