# Generated by Django 3.2.7 on 2022-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_scolarite_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='commentaire',
            field=models.CharField(max_length=250, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Fevrier', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Decembre', 'Decembre')], default=1, max_length=250, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.IntegerField(unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Fevrier', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Decembre', 'Decembre')], default=1, max_length=250, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='scolarite',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Fevrier', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Decembre', 'Decembre')], default=1, max_length=250, verbose_name='Mois'),
        ),
    ]
