# Generated by Django 3.2.7 on 2022-11-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_auto_20221118_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='matricule',
            field=models.IntegerField(unique=True, verbose_name='Matricule'),
        ),
    ]
