# Generated by Django 3.2.7 on 2022-11-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0044_auto_20221118_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='matricule',
            field=models.IntegerField(null=True, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.IntegerField(null=True, unique=True, verbose_name='Matricule'),
        ),
    ]
