# Generated by Django 3.2.7 on 2022-11-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_alter_etudiant_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.IntegerField(null=True, unique=True, verbose_name='Matricule'),
        ),
    ]
